name: Build IPEX base container
on:
  workflow_dispatch:
    inputs:
      whl_url:
        description: IPEX binary URL
        required: true

jobs:
  build-base-container:
    name: Build IPEX Base Container
    runs-on: k8-runners
    steps:
    - uses: docker/login-action@v3.3.0
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
    - name: Build Container
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        WHL_URL: ${{ inputs.whl_url }}
        REGISTRY: ${{ secrets.REGISTRY }}
      run: docker compose -f .github/docker/docker-compose.yml up --build ipex-cpu
