name: Functional Validation

on:
    workflow_dispatch:
      # inputs:
      #   cache_registry:
      #     description: 'Cache registry for the test runner'
      #     required: true
      #     default:
      #   recipe_dir:
      #     description: 'Directory containing the recipe'
      #     required: true
      #     default:
      #   registry:
      #     description: 'Registry for the test runner'
      #     required: true
      #     default:
      #   repo:
      #     description: 'Repository for the test runner'
      #     required: true
      #     default:
      #   test_dir:
      #     description: 'Directory containing the tests'
      #     required: true
      #     default:
      #   test_file:
      #     description: 'Test file to execute'
      #     required: true
      #     default: smoke.yaml

jobs:
    functional-validation:
        name: Functional Validation
        runs-on: k8-runners
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          # - name: Execute Test Runner
          #   uses: intel/ai-containers/test-runner@luis/test-runner-change
          #   with:
          #       cache_registry: ${{ secrets.CACHE_REGISTRY }}
          #       recipe_dir: ${{ secrets.RECIPE_DIR }}
          #       registry: ${{ secrets.REGISTRY }}
          #       repo: ${{ secrets.REPO }}
          #       test_dir: ${{ secrets.TEST_DIR }}
          #       test_file: ${{ secrets.TEST_FILE }}
          #       token: ${{ secrets.GITHUB_TOKEN }}
