name: Mirror sync-up
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: write-all
jobs:
  mirror-sync:
    name: Mirror sync-up
    runs-on: k8-runners
    steps:
      - name: Java Set Up
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Sync external repo
        id: mirror-repo
        run: |
          wget --quiet https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar
          git clone --single-branch --branch main \
            https://${{ github.actor }}:${{ github.token }}@github.com/intel-innersource/frameworks.ai.models.intel-models.git \
            airm-branches-subset
          cd airm-branches-subset
          BRANCHES='pytorch-r2.2-models pytorch-r2.3-models r3.4 r3.4.1'
          for branch in $BRANCHES; do git fetch origin $branch:$branch; done
          cd ..
          git clone --bare airm-branches-subset airm-branches-subset-bare
          cd airm-branches-subset-bare
          java -jar ../bfg-1.14.0.jar --delete-folders .github --delete-files .github --no-blob-protection
          git reflog expire --expire=now --all && git gc --prune=now --aggressive
          git push --mirror https://${{ secrets.TF_QA_PROD_GITHUB_USER_ID }}:${{ secrets.TF_QA_PROD_PUBLIC_TOKEN }}@github.com/intel/ai-reference-models.git
      - name: Cleanup
        if: always()
        run: |
          rm -fr airm-bare-main-branch*
          rm bfg-1.14.0.jar
