name: PR validations
on:
  pull_request: null
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks_setup:
    name: Setup checks
    runs-on: k8-runners
    outputs:
      checks: ${{ steps.set_checks.outputs.checks }}
    steps:
      - uses: actions/checkout@v4
      - name: Analyze changed files
        id: set_checks
        run:
          echo "checks=`python3 .github/utils/checks-setup.py
            -c .github/config/compliance-config.json
            -f smoke.yaml
            pr-check
            -u ${{ github.event.pull_request.url }}`" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print checks information
        run:
          echo ${{ toJson(steps.set_checks.outputs.checks) }} | jq
  bom_changes:
    name: BoM changes found
    needs: checks_setup
    runs-on: k8-runners
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_bom_change }}
    steps:
      - uses: actions/checkout@v4
      - name: Call BoM change action
        run:
          python3 .github/utils/comment-bom-changes.py
            -u '${{ github.event.pull_request.url }}'
            -j '${{ toJson(fromJson(needs.checks_setup.outputs.checks).files.bom) }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  containers_check:
    name: Build and Test Container
    needs: checks_setup
    runs-on: k8-runners
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_container_change }}
    strategy:
      matrix:
        container: ${{ fromJSON(needs.checks_setup.outputs.checks).services }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Up
        run: docker compose -p ${{ matrix.container.project }} -f ${{ matrix.container.file }} up --build ${{ matrix.container.service }}
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
      - name: Docker Compose Down
        if: always()
        run: docker compose -p ${{ matrix.container.project }} -f ${{ matrix.container.file }} down ${{ matrix.container.service }}
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
  smoke_test:
    name: Smoke Test Functional Validation
    needs: [checks_setup, containers_check]
    if: ${{ fromJson(needs.checks_setup.outputs.checks).flags.is_container_change }}
    runs-on: ${{ matrix.container.runner }}
    strategy:
      matrix:
        container: ${{ fromJSON(needs.checks_setup.outputs.checks).services }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: intel/ai-containers
          path: ai-containers
      - name: Install Requirements
        run: pip install -r ai-containers/test-runner/requirements.txt
      - name: Build Container
        run: docker compose -p ${{ matrix.container.project }} -f ${{ matrix.container.file }} build ${{ matrix.container.service }}
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
      - name: Check smoke test file
        run: test -f ${{ matrix.container.smoke }}
      - name: Execute Test Runner
        shell: bash
        run: python3 ai-containers/test-runner/test_runner.py -f ${{ matrix.container.smoke }}
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          TOKEN: ${{ secrets.HF_TOKEN }}
