name: Unit Test
on: pull_request
jobs:
  unit-test:
    runs-on: [k8-runners]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Test Dependencies
        run: |
          if [ -f "pyproject.toml" ]; then
            echo "pyproject.toml found, using Poetry to install dependencies."
            poetry install
          elif [ -f "requirements.txt" ]; then
            echo "requirements.txt found, using pip to install dependencies."
            pip install -r requirements.txt
          else
            echo "No pyproject.toml or requirements.txt found, skipping dependency installation."
          fi
      - name: Run Style Test using Make
        run: make lint
      - name: Run Unit Test
        run: make unit_test
